version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: eventstore/eventstore:release-4.0.3

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run: mvn test



